### ISSUE TITLE
Non-COSMOS Os

### ISSUE THREAD

**Issue by retrievaaaa** [CosmosOSProjectArchive/Claims#1]
This OS isn't Cosmos. It isn't an OS either.
Its a console app, even though the descriptions says otherwise.

Should be removed:
https://github.com/CosmosOSProjectArchive/NebulaOS

**Comment by jwoff78** [comment]
You are right, this was a missight it will be removed momentarily.

**Comment by jwoff78** [comment]
Addition to that, I apologize for the long reply time.
