### ISSUE TITLE
Takedown SipaaGL

### ISSUE THREAD

**Issue by raphm4044** [CosmosOSProjectArchive/Claims#2]
I want the takedown of SipaaGL's source code. I think the code added on PrismGL's codebase was very awful.

**Comment by jwoff78** [comment]
Sorry, I need permission from the original author.

**Comment by raphm4044** [comment]
The original author is me

**Comment by jwoff78** [comment]
This is correct, apologies, I'll remove it.

**Comment by raphm4044** [comment]
Thanks you.
