### ISSUE TITLE
Lynox addition maybe?

### ISSUE THREAD

**Issue by glintpry** [CosmosOSProjectArchive/Claims#3]
Lynox (https://github.com/PratyushKing/Lynox) is a project I made meant to be the most linux-like OS that follows a barebones way of doing stuff and I kinda wanna add it to the archive because if some day it's gone it should be in a backup as there going to be distributions for it. [One recently made is the Nebula Lynox {https://github.com/Samma2009/Nebula-Lynox}]

**Comment by jwoff78** [comment]
https://github.com/CosmosOSProjectArchive/Lynox
